### ISSUE TITLE
twitterwebsearch finds far less tweets than exist

### ISSUE THREAD

**Issue by wooblargl** [ShinNoNoir/twitterwebsearch#7]
Using the query `#HSVFCB lang:de since:2015-08-01 until:2016-01-25` (all tweets for a certain football game) twitterwebsearch finds 180 tweets. However Twitter's own web interface returns >1000 tweets.

Any idea why?

**Comment by ShinNoNoir** [comment]
Hmm, interestingly, that query breaks completely on one of my machines.

```
import traceback
import twitterwebsearch

tweets = []
try:
    for tweet in twitterwebsearch.search('#HSVFCB lang:de since:2015-08-01 until:2016-01-25'):
        tweets.append(tweet)
except:
    traceback.print_exc()

print '#tweets:', len(tweets)
```

Results in:

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "twitterwebsearch\searcher.py", line 63, in search
    for tweet in download_tweets(search=query):
  File "twitterwebsearch\searcher.py", line 49, in download_tweets
    min_position = response_dict['min_position']
KeyError: 'min_position'

#tweets: 0
```

So I'm curious, do you get any exceptions when running the example above?

(Pinging @egbertbouman for an extra set of eyes to look at the code.)

**Comment by wooblargl** [comment]
same

```
Traceback (most recent call last):
  File "foo.py", line 6, in <module>
    for tweet in twitterwebsearch.search('#HSVFCB lang:de since:2015-08-01 until:2016-01-25'):
  File "twitterwebsearch/twitterwebsearch/searcher.py", line 71, in search
    for tweet in download_tweets(search=query):
  File "twitterwebsearch/twitterwebsearch/searcher.py", line 57, in download_tweets
    min_position = response_dict['min_position']
KeyError: 'min_position'
#tweets: 0
```

URL encoding the hashtag fixes it though `%23HSVFCB lang:de since:2015-08-01 until:2016-01-25`

```
$ python foo.py
#tweets: 180
$
```

**Comment by ShinNoNoir** [comment]
Yes, I noticed that indeed. The user of this package should not have to encode their queries, so I have changed that in [branch issue7](https://github.com/ShinNoNoir/twitterwebsearch/tree/issue7).

Now, after applying this fix, I also get 180 tweets. Still far off the expected 1000+ tweets, though.

**Comment by ShinNoNoir** [comment]
This is just a hypothesis (since I did not work on the HTTP part of this package), but possibly it is a matter of throttling. This is the JSON that Twitter returns:

```
{
    "focused_refresh_interval": 30000, 
    "has_more_items": false, 
    "items_html": "(bunch of HTML)", 
    "min_position": "TWEET-some-identifier", 
    "new_latent_count": 1
}
```

@egbertbouman, do you remember the field `focused_refresh_interval` being returned before? My hunch is that Twitter simply refuses to return any results if too many requests are sent in a short interval.

**Comment by egbertbouman** [comment]
@ShinNoNoir No, I've never seen this field before. While implementing the HTTP requests, I've always used `sleep=1`, and never had any problems.

**Comment by ShinNoNoir** [comment]
Deciphering some parts of Twitter's behavior....
- The field `new_latent_count` seems to indicate the number of tweets encoded in `items_html`.
- When searching in the browser, the server sometimes responds with zero tweets. However, usually the next request will be answered with a few tweets again.
- When using a query that results in few results (such as in the README.md example), the webpage still occassionally sends requests to the server. The `min_position` in the responses seem to remain unchanged,  however.

_Possible solution to this issue:_ The implementation needs to check whether `min_position` changes between requests. If it changes, keep on querying. If it doesn't, return.

**Comment by ShinNoNoir** [comment]
I'm currently testing this idea (example test code is still running) and it seems to be working. Currently it has collected more than 8000 tweets....

...well, as I was typing this, the script finished:

```
#tweets: 8415
```

I will soon commit and push so you can test for yourself whether the last few commits will fix the issue.

**Comment by ShinNoNoir** [comment]
Latest changes are in https://github.com/ShinNoNoir/twitterwebsearch/commit/7ee0cbb15a32c96c50edf7ff18e3781033544c83. Run `pip install --upgrade https://github.com/ShinNoNoir/twitterwebsearch/archive/issue7.zip` to upgrade your installation.

I will keep this issue open until we can make sure this fixes the problem.

**Comment by wooblargl** [comment]
Works fine now - thank you for the quick fix :smile:

**Comment by ShinNoNoir** [comment]
Merged into main branch. :)
